#!/system/bin/sh

# ZRAM allocate 10% of device memory
# credit Imoseyon

if [ -e /data/data/com.android.settings/app_kk/zram_on_boot ]; then
    RAMSIZE=`grep MemTotal /proc/meminfo | awk '{ print \$2 }'`
    ZRAMSIZE=$(($RAMSIZE*100))

    echo $ZRAMSIZE > /sys/block/zram0/disksize && \
    /system/xbin/mkswap /dev/block/zram0 && \
    /system/xbin/swapon /dev/block/zram0 && \
    echo "500,1000,20000,20000,20000,25000" > /sys/module/lowmemorykiller/parameters/minfree
fi

# frequency control

files="/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq \
       /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq \
       /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq \
       /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq \
       /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor \
       /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor"

for x in $files; do
    chmod 664 $x
    chgrp system $x
done

if [ -e /data/data/com.android.settings/app_kk/clocks_on_boot ]; then
    thtt /data/local/kk_clocking
    TEST_VALUE=$?

    if [ ! $TEST_VALUE -eq 0 ]; then
        setprop kk.overclocking.failed 1
	log -t overclocking 'values not applied due to recent reboot'
    else

	if [ -e /data/data/com.android.settings/app_kk/clocks_min ]; then
		cat /data/data/com.android.settings/app_kk/clocks_min > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
		cat /data/data/com.android.settings/app_kk/clocks_min > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
	fi

        if [ -e /data/data/com.android.settings/app_kk/clocks_max ]; then
                cat /data/data/com.android.settings/app_kk/clocks_max > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
                cat /data/data/com.android.settings/app_kk/clocks_max > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
        fi

        if [ -e /data/data/com.android.settings/app_kk/clocks_gov ]; then
                cat /data/data/com.android.settings/app_kk/clocks_gov > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
                cat /data/data/com.android.settings/app_kk/clocks_gov > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
        fi

        
    fi;
fi

# I/O scheduler
chgrp system /sys/block/mmcblk0/queue/scheduler
chmod 664 /sys/block/mmcblk0/queue/scheduler

# Sweep2Wake if kernel supports it
chgrp system /sys/android_touch/sweep2wake
chmod 664 /sys/android_touch/sweep2wake

# USB fast charge, we just set perms. This is likely
# not something we want to set on boot
chgrp system /sys/kernel/fast_charge/force_fast_charge
chmod 664 /sys/kernel/fast_charge/force_fast_charge


